In [7]:
import numpy as np 
from numpy.random import seed
#seed(1)


train_data = np.array([[1.0,1.0]])

train_targets = np.array([2.0])

print(train_data)
print(train_targets)

for i in range(3,10000,2):
    train_data= np.append(train_data,[[i,i]],axis=0)

    train_targets= np.append(train_targets,[i+i])

print("train_data")
print(train_data)
print(train_targets)

stop = input()
test_data = np.array([[2.0,2.0]])

test_targets = np.array([4.0])

for i in range(4,8000,4):

    test_data = np.append(test_data,[[i,i]],axis=0)

    test_targets = np.append(test_targets,[i+i])
print("test_data")
print(test_data)
print(test_targets)

[[1. 1.]]
[2.]
train_data
[[1.000e+00 1.000e+00]
 [3.000e+00 3.000e+00]
 [5.000e+00 5.000e+00]
 ...
 [9.995e+03 9.995e+03]
 [9.997e+03 9.997e+03]
 [9.999e+03 9.999e+03]]
[2.0000e+00 6.0000e+00 1.0000e+01 ... 1.9990e+04 1.9994e+04 1.9998e+04]
1
test_data
[[2.000e+00 2.000e+00]
 [4.000e+00 4.000e+00]
 [8.000e+00 8.000e+00]
 ...
 [7.988e+03 7.988e+03]
 [7.992e+03 7.992e+03]
 [7.996e+03 7.996e+03]]
[4.0000e+00 8.0000e+00 1.6000e+01 ... 1.5976e+04 1.5984e+04 1.5992e+04]


In [11]:

	
#model

import tensorflow as tf
#tf.random.set_seed(2)
from tensorflow import keras

model = keras.Sequential([

    keras.layers.Flatten(input_shape=(2,)),

    keras.layers.Dense(4, activation=tf.nn.relu),

    keras.layers.Dense(1)

])


model.compile(optimizer='adam', 

              loss='mse',

              metrics=['mae'])

for layer in model.layers: 
  print(layer.get_config(), layer.get_weights())




{'name': 'flatten_2', 'trainable': True, 'dtype': 'float32', 'batch_input_shape': (None, 2), 'data_format': 'channels_last'} []
{'name': 'dense_4', 'trainable': True, 'dtype': 'float32', 'units': 4, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None} [array([[ 0.9707751 , -0.06461024, -0.2755301 , -0.5008004 ],
       [ 0.2500186 , -0.2941277 ,  0.14966512, -0.16229177]],
      dtype=float32), array([0., 0., 0., 0.], dtype=float32)]
{'name': 'dense_5', 'trainable': True, 'dtype': 'float32', 'units': 1, 'activation': 'linear', 'use_bias': True, 'kernel_initializer': {'class_name': 'GlorotUniform', 'config': {'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer'

In [12]:

values = np.array([[2000,3000],[4,5]])

sommes = model.predict(values)
print (values[0][0],"+",values[0][1],"=",sommes[0][0])
print (values[1][0],"+",values[1][1],"=",sommes[1][0])
stop = input()


1/1 [==============================] - 0s 95ms/step
2000 + 3000 = 2674.4878
4 + 5 = 5.1005473
1


In [14]:

model.fit(train_data, train_targets, epochs=10, batch_size=1)

sommes = model.predict(values)
print (values[0][0],"+",values[0][1],"=",sommes[0][0])
print (values[1][0],"+",values[1][1],"=",sommes[1][0])

stop = input()

test_loss, test_acc = model.evaluate(test_data, test_targets)

print('Test accuracy:', test_acc)




Epoch 1/2
5000/5000 [==============================] - 10s 2ms/step - loss: 18.2208 - mae: 1.3125
Epoch 2/2
1/1 [==============================] - 0s 26ms/step
2000 + 3000 = 4563.519
4 + 5 = 8.603046
1
63/63 [==============================] - 0s 3ms/step - loss: 6.1676e-04 - mae: 0.0229
Test accuracy: 0.022862210869789124
